apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-latest
  namespace: devops-tools
  labels:
    app: nginx
spec:
  replicas: 1 # Nombre de pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Image Docker de NGINX
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: devops-tools
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Port exposé par le service
      targetPort: 80 # Port dans le conteneur
  type: NodePort # Type de service modifié en NodePort
